### ISSUE TITLE
launcher window does not remember the height and width

### ISSUE THREAD

**Issue by bc38** [nohal/launcher_pi#7]
The launcher window does not remember the height and width
Build from latest sources
Windows
![2019-05-06 014224](https://user-images.githubusercontent.com/7856184/57211677-c1d28680-7013-11e9-810e-e756c8af2d34.jpg)

**Comment by bc38** [comment]
So they did not fix the bug by displaying the window on WIN((((

**Comment by kelld00** [comment]
I'm seeing this same issue with the latest version of Raspbian and OpenCPN on a RPI4 too. Any idea how to get this working so I can use it?

**Comment by bc38** [comment]
the problem has not been resolved! (((((

**Comment by Fgonzalez22** [comment]
The problem continues, its very unfortunate given launcher so useful

**Comment by nohal** [comment]
You may grab the latest build from https://cloudsmith.io/~nohal/repos/opencpn-plugins/packages/ as far as I can tell the problem is fixed.

**Comment by Fgonzalez22** [comment]
Hi Pavel. Thanks for your reply. Im using Launcher v1.3.5 for OCPN, the latest but the problem persists.

 

 

 

De: Pavel Kalian ***@***.*** 
Enviado el: lunes, 17 de junio de 2024 21:19
Para: nohal/launcher_pi
CC: Fgonzalez22; Comment
Asunto: Re: [nohal/launcher_pi] launcher window does not remember the height and width (#7)

 

You may grab the latest build from https://cloudsmith.io/~nohal/repos/opencpn-plugins/packages/ as far as I can tell the problem is fixed.

**Comment by nohal** [comment]
The latest from https://cloudsmith.io/~nohal/repos/opencpn-plugins/packages/ I linked above or the latest available from the plugin manager?

**Comment by Fgonzalez22** [comment]
I mean the latest from the plugin. (It says 1.3.5 vs 1.3 from clout smith). If that is not the correct, I’m not very proficient and don’t know how to proceed.

 

De: Pavel Kalian ***@***.*** 
Enviado el: miércoles, 19 de junio de 2024 16:16
Para: nohal/launcher_pi
CC: Fgonzalez22; Comment
Asunto: Re: [nohal/launcher_pi] launcher window does not remember the height and width (#7)

 

The latest from https://cloudsmith.io/~nohal/repos/opencpn-plugins/packages/ I linked above or the latest available from the plugin manager?

**Comment by nohal** [comment]
Download the latest tarball for your platform  from cloudsmith repository I linked and import it in the plugin manager.

**Comment by Fgonzalez22** [comment]
I dowloaded Launcher-1.3.6+412.b1c2f86_debian-wx32-11-arm64.tar.gz

 

I get “incompatible pluggin import detected” when importing into the pluggin catalog

 

Im running OpenCPN 5.8.4+8089+1637c28fb~ubuntu20.04.1 ; 64 bits

 

Am I downloading wrong file?

 

 

 

De: Pavel Kalian ***@***.*** 
Enviado el: miércoles, 19 de junio de 2024 16:31
Para: nohal/launcher_pi
CC: Fgonzalez22; Comment
Asunto: Re: [nohal/launcher_pi] launcher window does not remember the height and width (#7)

 

Download the latest tarball for your platform from cloudsmith repository I linked and import it in the plugin manager.

**Comment by Fgonzalez22** [comment]
Hi Pavel, I dowloaded Launcher-1.3.6+412.b1c2f86_debian-wx32-11-arm64.tar.gz

I get “incompatible pluggin import detected” when importing into the pluggin catalog

Im running OpenCPN 5.8.4+8089+1637c28fb~ubuntu20.04.1 ; 64 bits

Am I downloading wrong file?

**Comment by nohal** [comment]
Likely, OpenCPN 5.8.4+8089+1637c28fb~ubuntu20.04.1 is probably built against wxWidgets 3.0, so it needs the plugin without `wx32` (which means that plugin build was done against wxWidgets 3.2) in the name.

**Comment by Fgonzalez22** [comment]
No luck, I always get the same incompatibility message, any chance the opencpn catalog might be updated with the latest version with the problem solved?

**Comment by nohal** [comment]
As soon as https://github.com/OpenCPN/plugins/pull/1130 is merged

**Comment by nohal** [comment]
BTW, are you on ARM64 at all?

**Comment by Fgonzalez22** [comment]
i think so, im running OpenCPN 5.8.4+8089+1637c28fb~ubuntu20.04.1 ; 64 bits

**Comment by nohal** [comment]
It tells nothing about the architecture of your machine. To put it simple, are you using a PC or a Raspberry Pi?

**Comment by Fgonzalez22** [comment]
Im using a raspberry pi 3b

 

De: Pavel Kalian ***@***.*** 
Enviado el: miércoles, 26 de junio de 2024 9:10
Para: nohal/launcher_pi
CC: Fgonzalez22; Comment
Asunto: Re: [nohal/launcher_pi] launcher window does not remember the height and width (#7)

 

It tells nothing about the architecture of your machine. To put it simple, are you using a PC or a Raspberry Pi?
